const quotes = [
  { quote: "I'm Just a Extreme example of what a working man can achieve", author: "Tommy Shelby" },
  { quote: "I'm not god, not yet", author: "Tommy Shelby" },
  { quote: "There's no Rest for me in this world, perhaps the next", author: "Tommy Shelby" },
  { quote: "When you plan something well, there's no need to rush", author: "Tommy Shelby" },
  { quote: "The only way to guarantee peace is by making the prospect of war seem hopeless.", author: "Tommy Shelby" },
  { quote: "I have no limitations", author: "Tommy Shelby" },
  
  { quote: "Power is knowing who you are and where you come from", author: "Alfie Solomons" },
  { quote: "I don't ask for respect. I command it", author: "Alfie Solomons" },
  { quote: "Every man, he craves certainty", author: "Alfie Solomons" },
  { quote: "He'll wake up. Granted, He won't have any teeth left, but he will be a wiser Man for it.", author: "Alfie Solomons" },
  { quote: "Money is just paper, and all the rest is just a dream", author: "Alfie Solomons" },
  { quote: "In this world, a man, himself, is nothing. And there ain’t no world but this one", author: "Alfie Solomons" },
  
  { quote: "This is your life, and it’s ending one minute at a time", author: "Tyler Durden" },
  { quote: "You are not your job. You are not how much money you have in the bank", author: "Tyler Durden" },
  { quote: "What you are is what you have been. What you’ll be is what you do now", author: "Tyler Durden" },
  { quote: "Self-improvement is masturbation", author: "Tyler Durden" },
  { quote: "Life is not about how much you have, but how much you give", author: "Tyler Durden" },
  { quote: "People are always asking me if I’m afraid of death. I’m more afraid of wasting my life", author: "Tyler Durden" },
  { quote: "Stop trying to control everything, and just let go", author: "Tyler Durden" },
  { quote: "Reject the basic assumptions of civilization, especially the importance of material possessions", author: "Tyler Durden" },
  { quote: "The things you own end up owning you", author: "Tyler Durden" },
  { quote: "We buy things we don’t need with money we don’t have to impress people we don't like", author: "Tyler Durden" },
  
  { quote: "Death created time to grow the things that it would kill.", author: "Rustin Cohle" },
  { quote: "Well, once there was only dark. If you ask me, the light's winning.", author: "Rustin Cohle" },
  { quote: "People incapable of guilt usually do have a good time.", author: "Rustin Cohle" },
  { quote: "I don’t sleep. I just dream", author: "Rustin Cohle" },
  { quote: "I’d consider myself a realist, all right? But in philosophical terms, I’m what’s called a pessimist", author: "Rustin Cohle" },
  { quote: "Life’s barely long enough to get good at one thing. So be careful what you get good at", author: "Rustin Cohle" },
  { quote: "The world needs bad men. We keep the other bad men from the door.", author: "Rustin Cohle" },
  { quote: "I know who I am. And after all these years, there’s a victory in that.", author: "Rustin Cohle" },
  
  { quote: "If it’s war they want--I’ve got just the thing", author: "Bruce Wayne" },
  { quote: "The Idea Was To Be A Symbol…", author: "Bruce Wayne" },
  { quote: "It’s Not Who I Am Underneath, But What I Do That Defines Me", author: "Bruce Wayne" },
  { quote: "Sometimes it's only madness that makes us what we are", author: "Bruce Wayne" },
  { quote: "They Can Give Us The Power To Endure, And The Strength To Fight", author: "Bruce Wayne" },
  { quote: "The world only makes sense if you force it to", author: "Bruce Wayne" },
  { quote: "I have one power. I never give up", author: "Bruce Wayne" },
  { quote: "Whatever doesn’t kill you, simply makes you stronger", author: "Bruce Wayne" },
  { quote: "All men have limits. They learn what they are and learn not to exceed them. I ignore mine", author: "Bruce Wayne" },
  { quote: "As a man; I am flesh and blood. I can be ignored, I can be destroyed, But as a symbol, I can be incorruptible, I can be everlasting", author: "Bruce Wayne" },
  { quote: "Our greatest glory is not in ever falling, but in rising every time we fall", author: "Bruce Wayne" },
  
  { quote: "Work until you no longer have to introduce yourself", author: "Harvey Specter" },
  { quote: "You want to change your life? Change the way you think", author: "Harvey Specter" },
  { quote: "I don’t have dreams, I have goals.", author: "Harvey Specter" },
  { quote: "It’s going to happen because I am going to make it happen", author: "Harvey Specter" },
  { quote: "When you are backed against the wall, bring the goddamn thing down", author: "Harvey Specter" },
  { quote: "Winners don’t make excuses", author: "Harvey Specter" },
  { quote: "Have goals so big you get uncomfortable telling small-minded people", author: "Harvey Specter" },
  { quote: "I don’t get lucky, I make my own luck.", author: "Harvey Specter" },
  { quote: "You always have a choice", author: "Harvey Specter" },
  { quote: "You wanna lose small, I wanna win big", author: "Harvey Specter" },
  { quote: "The only time success comes before work is in dictionary", author: "Harvey Specter" },
  
  { quote: "If you are good at something, never do it for free", author: "Joker" },
  { quote: "Nobody panics when everything goes ‘according to the plan’, even if the plan is horrifying!", author: "Joker" },
  { quote: "Why so serious?", author: "Joker" },
  { quote: "Smile, because it confuses people. Smile, because it’s easier than explaining what is killing you inside", author: "Joker" },
  { quote: "Some people want to see you fail. Disappoint them!", author: "Joker" },
  
  { quote: "The World is yours!", author: "Tony Montana" },
  { quote: "In this country, you gotta make the money first, then when you get the money, you get the power.", author: "Tony Montana" },
  { quote: "You’re not good, you just know how to hide, how to lie", author: "Tony Montana" },
  { quote: "I work hard for this, I want you to know that", author: "Tony Montana" },
  { quote: "Who put this thing together? Me, that’s who! Who do I trust? Me!", author: "Tony Montana" },
  
  { quote: "There’s no room for softness. No place for weakness. Only the hard and strong may call themselves Spartans", author: "King Leonidas" },
  { quote: "No retreat, no surrender", author: "King Leonidas" },
  { quote: "Spartans! Prepare for glory!", author: "King Leonidas" },
  { quote: "Give them nothing! But take from them everything", author: "King Leonidas" },

  // PHILOSOPHERS
  
  { quote: "Start with what is right rather than what is acceptable.", author: "Franz Kafka" },
  { quote: "It's only because of their stupidity that they're able to be so sure of themselves.", author: "Franz Kafka" },
  { quote: "Better to have, and not need, than to need, and not have.", author: "Franz Kafka" },
  { quote: "Isolation is a way to know ourselves.", author: "Franz Kafka" },
  { quote: "Do not waste your time looking for an obstacle - maybe there is none.", author: "Franz Kafka" },

  { quote: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", author: "Fyodor Dostoevsky" },
  { quote: "The best way to keep a prisoner from escaping is to make sure he never knows he's in prison.", author: "Fyodor Dostoevsky" },
  { quote: "It is better to be unhappy and know the worst, than to be happy in a fool's paradise.", author: "Fyodor Dostoevsky" },
  { quote: "But how could you live and have no story to tell?", author: "Fyodor Dostoevsky" },
  { quote: "If you want to overcome the whole world, overcome yourself.", author: "Fyodor Dostoevsky" },
  { quote: "To think too much is a disease.", author: "Fyodor Dostoevsky" },
  { quote: "I gave up caring about anything, and all the problems disappeared.", author: "Fyodor Dostoevsky" },
  { quote: "You will burn and you will burn out; you will be healed and come back again.", author: "Fyodor Dostoevsky" },
  { quote: "It takes something more than intelligence to act intelligently.", author: "Fyodor Dostoevsky" },
  { quote: "What is hell? I maintain that it is the suffering of being unable to love.", author: "Fyodor Dostoevsky" },
  { quote: "You can be sincere and still be stupid.", author: "Fyodor Dostoevsky" },

  { quote: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", author: "Friedrich Nietzsche" },
  { quote: "There are two different types of people in the world, those who want to know, and those who want to believe.", author: "Friedrich Nietzsche" },
  { quote: "Those who are devoid of purpose will make the void their purpose.", author: "Friedrich Nietzsche" },
  { quote: "The higher we soar the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
  { quote: "Nothing on earth consumes a man more quickly than the passion of resentment.", author: "Friedrich Nietzsche" },
  { quote: "No price is too high to pay for the privilege of owning yourself.", author: "Friedrich Nietzsche" },
  { quote: "There's no defense against stupidity.", author: "Friedrich Nietzsche" },
  { quote: "And once you are awake, you shall remain awake eternally.", author: "Friedrich Nietzsche" },
  { quote: "Love your enemies because they bring out the best in you.", author: "Friedrich Nietzsche" },

  { quote: "If you are lonely when you're alone, you are in bad company.", author: "Jean-Paul Sartre" },
  { quote: "We are our choices.", author: "Jean-Paul Sartre" },
  { quote: "Freedom is what you do with what's been done to you.", author: "Jean-Paul Sartre" },
  { quote: "There may be more beautiful times, but this one is ours.", author: "Jean-Paul Sartre" },
  { quote: "Introspection is always retrospection", author: "Jean-Paul Sartre" },
  { quote: "Man is nothing else but what he makes of himself.", author: "Jean-Paul Sartre" },

  { quote: "Life is meaningless, but worth living, provided you recognize it's meaningless.", author: "Albert Camus" },
  { quote: "Life is a sum of all your choices. So, what are you doing today?", author: "Albert Camus" },
  { quote: "Sometimes, carrying on, just carrying on, is the superhuman achievement.", author: "Albert Camus" },
  { quote: "Where there is no hope, we must invent it.", author: "Albert Camus" },
  { quote: "The realization that life is absurd cannot be an end, but only a beginning.", author: "Albert Camus" },
  { quote: "I would rather live my life as if there is a God and die to find out there isn't, than live as if there isn't and to die to find out that there is.", author: "Albert Camus" },
  { quote: "I rebel; therefore I exist.", author: "Albert Camus" },
  { quote: "The greatness of man lies in his decision to be stronger than his condition.", author: "Albert Camus" },
  { quote: "Those who lack the courage will always find a philosophy to justify it.", author: "Albert Camus" },

  { quote: "Life can only be understood backwards; but it must be lived forwards.", author: "Søren Kierkegaard" },
  { quote: "The most common form of despair is not being who you are.", author: "Søren Kierkegaard" },
  { quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard" },
  { quote: "Take a chance and you may lose. Take not a chance and you have lost already.", author: "Søren Kierkegaard" },
  { quote: "Do it or don't do it - you will regret both.", author: "Søren Kierkegaard" },
  { quote: "Face the facts of being what you are, for that is what changes what you are.", author: "Søren Kierkegaard" },
  { quote: "The most painful state of being is remembering the future, particularly the one you'll never have.", author: "Søren Kierkegaard" }
];

